### ISSUE TITLE
Some PHP notices fixed

### ISSUE THREAD

**Issue by linksmith** [Sk-Shaikat/woocommerce-upcoming-product#3]
In `woocommerce-upcoming-product.php`

PHP Notices fixed that occur in `wup_stop_adding_to_cart` (because `$post` is not available at this point and has not been set).

I fixed this by using `$product_id` in stead.

Also fixed references to $this made from a static context around line 340 and 348:
`$this->wup_maybe_add_category_args` and `$this->wup_product_loop`

changed to:

`Woocommerce_Upcoming_Product::wup_maybe_add_category_args` and
`Woocommerce_Upcoming_Product::wup_product_loop`

Are you open to pull requests?

**Comment by linksmith** [comment]
Also I added a `$post != null` check to `is_upcoming()` to since it is also running on pages without posts, and also fires a PHP Notice.

**Comment by Mohaiminulislam1989** [comment]
Thank you for the issue. Really appreciate this.
This repo is always open for a pull request. I have fixed those issue you noticed.
