### ISSUE TITLE
Unable to activate the plugin

### ISSUE THREAD

**Issue by srijidhmadhavan** [Sk-Shaikat/woocommerce-upcoming-product#4]
Hi,

When I tried to activate the plugin I got the following error:
Fatal error: Can't use function return value in write context in /**/wp-content/plugins/woocommerce-upcoming-product/woocommerce-upcoming-product.php on line 689

**Comment by Mohaiminulislam1989** [comment]
The issue has been fixed in the latest update.
Please check: https://wordpress.org/support/topic/fatal-error-2655/
